In [3]:
import numpy as np
import math

pic = []
pic = np.array( [ (0,0,0,0,0,0,0,0,0,0), 
                  (0,1,1,1,1,0,0,0,1,1),
                  (0,0,1,1,1,0,1,1,1,1),
                  (0,0,1,1,0,0,1,1,1,1),
                  (0,1,1,1,0,0,1,1,1,0),
                  (0,0,0,0,0,0,0,0,1,0),
                  (0,0,0,1,1,1,0,0,1,0),
                  (0,0,0,1,1,1,1,0,0,0),
                  (0,0,0,1,1,1,1,0,0,0),
                  (0,0,0,0,0,0,1,0,0,0) ], dtype = int )

# ()
#print(pic)

islands = np.zeros( (100,100), dtype=np.int )
num_island=0
area_number=1
area_island=[]
count = 0   #for buffer
cal = 0     #for cal areas
buffer_island = np.zeros( (20,2), dtype=np.int )

for i in range(10) :
    for j in range(10) :
        if pic[i][j] == 1 :
            cal=0
            num_island = num_island +1
            pic[i][j]=2
            islands[num_island][i*10+j]=1
            cal = cal + 1
            count = 0
            num=0
            # 判斷四周
            if(j+1)<=9 :
                if pic[i][j+1] == 1 :
                    count =count + 1
                    pic[i][j+1]=2
                    islands[num_island][(i)*10+(j+1)]=1
                    buffer_island[cal-1][0] = i
                    buffer_island[cal-1][1] = j+1
                    cal = cal + 1
            if(i+1)<=9 :
                if pic[i+1][j] == 1 :
                    count =count + 1
                    pic[i+1][j]=2
                    islands[num_island][(i+1)*10+(j)]=1
                    buffer_island[cal-1][0] = i+1
                    buffer_island[cal-1][1] = j
                    cal = cal + 1
            if(j-1)>=0 :
                if pic[i][j-1] == 1 :
                    count =count + 1
                    pic[i][j-1]=2
                    islands[num_island][(i)*10+(j-1)]=1
                    buffer_island[cal-1][0] = i
                    buffer_island[cal-1][1] = j-1
                    cal = cal + 1
            while( count!=0 ) :
                x=buffer_island[num][0]
                y=buffer_island[num][1]
                pic[x][y]=2
                islands[num_island][(x)*10+(y)]=1
                count = count - 1
                if(y+1)<=9 :
                    if pic[x][y+1] == 1 :
                        count =count + 1
                        pic[x][y+1]=2
                        islands[num_island][(x)*10+(y+1)]=1
                        buffer_island[cal-1][0] = x
                        buffer_island[cal-1][1] = y+1
                        cal = cal + 1
                if(x+1)<=9 :
                    if pic[x+1][y] == 1 :
                        count =count + 1
                        pic[x+1][y]=2
                        islands[num_island][(x+1)*10+(y)]=1
                        buffer_island[cal-1][0] = x+1
                        buffer_island[cal-1][1] = y
                        cal = cal + 1
                if(y-1)>=0 :
                    if pic[x][y-1] == 1 :
                        count =count + 1
                        pic[x][y-1]=2
                        islands[num_island][(x)*10+(y-1)]=1
                        buffer_island[cal-1][0] = x
                        buffer_island[cal-1][1] = y-1
                        cal = cal + 1
                num = num +1
            #area_island[num_island-1]=cal
            area_island.append( [cal] )
            
# 圖片分塊結束

for b in range( num_island ):
    for c in range( 10 ):
        print( islands[b+1][c*10:c*10+10] )
    print( 'Area = ', area_island[b] )
    print( ' ' )

    


[0 0 0 0 0 0 0 0 0 0]
[0 1 1 1 1 0 0 0 0 0]
[0 0 1 1 1 0 0 0 0 0]
[0 0 1 1 0 0 0 0 0 0]
[0 1 1 1 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
Area =  [12]
 
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 1]
[0 0 0 0 0 0 1 1 1 1]
[0 0 0 0 0 0 1 1 1 1]
[0 0 0 0 0 0 1 1 1 0]
[0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
Area =  [15]
 
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 1 1 1 0 0 0 0]
[0 0 0 1 1 1 1 0 0 0]
[0 0 0 1 1 1 1 0 0 0]
[0 0 0 0 0 0 1 0 0 0]
Area =  [12]
 
